
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERREGESTRATION-SERVICE
          uri: lb://USERREGESTRATION-SERVICE
          predicates:
            - path= /user/**
          
        - id: USERLOGIN-SERVICE
          uri: lb://USERLOGIN-SERVICE
          predicates:
            - path= /login/**
        
            
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - path= /product/**
        
        
        - id: PRODUCTCATEGORY-SERVICE
          uri: lb://PRODUCTCATEGORY-SERVICE
          predicates:
            - path= /productCat/**
          
            
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - path= /cart/**
          
           
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - path= /order/**
          